### ISSUE TITLE
CSE_ModbusRTU.h does not have a define check

### ISSUE THREAD

**Issue by LukeSkaff** [CIRCUITSTATE/CSE_ModbusRTU#8]
I noticed when I included CSE_ModbusRTU.h in a class cpp file the compiler errored out do to double define.  I see there is no #ifndef in CSE_ModbusRTU.h, may be nice to have.

Other functions that would be helpful for debug would be a functions that returns the address block and count of the each register type.  I know it is defined when configuring coils but I was getting some weird responses at times that would be helpful to be able to get access to that count to make sure it got setup correctly.

**Comment by vishnumaiea** [comment]
Yes Luke. Will add that soon.
